services:
    eliza:
        command: ["pnpm", "start"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./data:/app/data
        environment:
            - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
            - DISCORD_API_TOKEN=${DISCORD_API_TOKEN}
            - HEURIST_API_KEY=${HEURIST_API_KEY}
            - AGENT_ADDRESS=${AGENT_ADDRESS}
            - AGENT_PRIVATE_KEY=${AGENT_PRIVATE_KEY}
        ports:
            - "3000:3000"
        restart: always
